version: '3'
services:
    db:
        image: postgres:9.6
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

    redis:
        image: redis:3
        ports:
            - "6379:6379"

    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"

volumes:
    db_data:
    es_data:
